modded class GameConstants
{
	//! Thin-air hypoxia (Sakhal): reduces stamina cap above PLAYZ_SAKHAL_HYPOXIA_ALT_START_M.
	const float PLAYZ_SAKHAL_HYPOXIA_ALT_START_M = 250.0;
	const float PLAYZ_SAKHAL_HYPOXIA_ALT_FULL_M = 570.0;
	const float PLAYZ_SAKHAL_HYPOXIA_CAP_PENALTY_MAX = 60.0;
	const float PLAYZ_SAKHAL_HYPOXIA_SOFT_PPE_PARTIAL_MUL = 0.40;

	const float PLAYZ_SAKHAL_HYPOXIA_CLIENT_CHROM_MAX = 0.05;
	const float PLAYZ_SAKHAL_HYPOXIA_CLIENT_BLUR_MAX = 0.30;
	const float PLAYZ_SAKHAL_HYPOXIA_PPE_FADE_SEC = 1.0;
	const float PLAYZ_SAKHAL_HYPOXIA_CLIENT_REST_PPE_MUL = 0.52;
	const float PLAYZ_SAKHAL_HYPOXIA_CLIENT_SPRINT_PPE_MUL = 1.85;

	const float PLAYZ_SAKHAL_HYPOXIA_SOUND_COOLDOWN_MS = 4200;
}
