static const int RPC_PLAYZ_AC_CAMERA_REQUEST  = 264001;
static const int RPC_PLAYZ_AC_CAMERA_RESPONSE = 264002;
static const int RPC_PLAYZ_AC_KEYBIND_REPORT  = 264003;
static const int RPC_PLAYZ_AC_KICK_MESSAGE    = 264004;
static const int PLAYZ_AC_CAMERA_FLAG_DETACHED = 1;
static const int PLAYZ_AC_KEYBIND_FLUSH_SECONDS = 1;
static const int PLAYZ_AC_KEYBIND_MAX_COUNT_DISPLAY = 999;
static const int PLAYZ_AC_KEYBIND_MAX_PAYLOAD_CHARS = 256;
